### ISSUE TITLE
Uma tracker correcterファイルについて

### ISSUE THREAD

**Issue by shmpwk** [UMATracker/UMATracker#8]
Uma tracker trackingでは、追跡完了後にCSVファイル、colorファイル、txtファイルが出力されると思います。
しかし、Uma tracker corrector においてはCSVファイル、JSONファイル、colorファイルの3ファイルを開くように要求されているため、UMA tracker correctorが使用できない状況です。

対処法についてご教授ください。

**Comment by Licht-T** [comment]
ありがとうございます。

動画ファイルの読み込みがFileメニュー存在しませんね。

ワークアラウンドですが、CSVファイルを読み込んだあと、解析に使っている動画ファイルをWindowにドラッグ・アンド・ドロップすると、ビデオが読み込まれて正しく動作するようになります。

https://umatracker.github.io/UMATracker-manual/_md/quick_ref.html#data-correction

**Comment by Licht-T** [comment]
@ymnk13 ちょっと忙しいから、時間があったらなおして

**Comment by shmpwk** [comment]
ありがとうございます。無事できました。

2019年12月13日(金) 1:20 Licht Takeuchi <notifications@github.com>:
