### ISSUE TITLE
位置座標について

### ISSUE THREAD

**Issue by shmpwk** [UMATracker/UMATracker#9]
お世話になります。
トラッキングで出力される位置座標の単位を教えていただけないでしょうか。

**Comment by Licht-T** [comment]
動画左上を原点、単位はピクセルです。

メートルに戻すときは以下を参考にしてください。
https://github.com/UMATracker/UMATracker/wiki/FAQ#how-to-convert-the-data-to-the-real-world-scale

**Comment by shmpwk** [comment]
ご回答ありがとうございます．
